services:
    davmail:
        container_name: davmail
        hostname: davmail
        image: davmail
        restart: unless-stopped
        ports:
            - 127.0.0.1:1025:1143 # SMTP
            - 127.0.0.1:1143:1143 # IMAP
        volumes:
            - ./davmail.properties:/davmail.properties
#            - ./davmail.p12:/davmail.p12 # uncomment for SSL (see README.md)
